services:
  warehouse:
    image: postgres:16
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_pass
      POSTGRES_DB: banking_dw
    ports:
      - "5433:5432"

  airflow:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      - warehouse
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "dbt-postgres==1.8.0"
    ports:
      - "8080:8080"
    command: standalone