services:
  warehouse:
    image: postgres:16
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_pass
      POSTGRES_DB: banking_dw
    ports:
      - "5433:5432"

  airflow:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    depends_on:
      - warehouse
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    command: standalone